import { Inter } from "next/font/google";
import "./globals.css";
import Header from "@/components/header";
import { ThemeProvider } from "@/components/theme-provider";
import { dark } from "@clerk/themes"
import { ClerkProvider } from "@clerk/nextjs";
import { Toaster } from "sonner";


const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: "Medical Management System",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <ClerkProvider
      appearance={{
        baseTheme: dark,
      }}
    >
      <html lang="en" suppressHydrationWarning>

        <body className={`${inter.className}`} >

          <ThemeProvider
            attribute="class"
            defaultTheme="dark"
            enableSystem
            disableTransitionOnChange
          >
            {/* Header */}
            <Header />

            <main className="min-h-screen">
              {children}
            </main>
            <Toaster richColors />

            {/* footer */}
            <footer className="bg-muted/50 py-2">
              <div className="container mx-auto px-4 text-sm italic text-center text-gray-200">
                <p>
                  2025 Medical Management System
                </p>
              </div>
            </footer>
          </ThemeProvider>

        </body>

      </html>
    </ClerkProvider>
  );
}
